import { createContext, useContext, useState } from "react";
import type { ReactNode } from "react";

export type Language = "ru" | "en" | "cs";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    "nav.home": "Главная",
    "nav.calculator": "Калькулятор",
    "nav.workouts": "Тренировки",
    
    // Hero
    "hero.badge": "Персональный расчёт за 1 минуту",
    "hero.title": "Рассчитай дневную норму",
    "hero.titleHighlight": "калорий",
    "hero.titleEnd": "и получи план тренировок",
    "hero.subtitle": "Научно обоснованные формулы и персональные рекомендации для достижения ваших целей — похудение, набор массы или поддержание формы",
    "hero.cta": "Начать расчёт",
    "hero.secondary": "Смотреть тренировки",
    "hero.users": "пользователей",
    "hero.exercises": "упражнений",
    "hero.rating": "рейтинг",

    // Features
    "features.title": "Всё для вашего результата",
    "features.subtitle": "Три ключевых инструмента, которые работают вместе для достижения вашей цели",
    "features.formula.title": "Точная формула",
    "features.formula.desc": "Расчёт по Mifflin-St Jeor с учётом вашего уровня активности, возраста и целей. Получите персональные рекомендации по калориям и БЖУ.",
    "features.workouts.title": "Персональные тренировки",
    "features.workouts.desc": "Готовые программы для дома и зала с учётом типа телосложения. Выберите оборудование, уровень подготовки — и получите недельный план.",
    "features.tracking.title": "Типы телосложения",
    "features.tracking.desc": "Программы адаптированы под эктоморфов, мезоморфов и эндоморфов согласно рекомендациям ACSM и NSCA.",

    // Calculator
    "calc.title": "Калькулятор калорий",
    "calc.formula": "Формула Mifflin-St Jeor",
    "calc.gender": "Пол",
    "calc.male": "Мужской",
    "calc.female": "Женский",
    "calc.age": "Возраст",
    "calc.height": "Рост",
    "calc.weight": "Вес",
    "calc.activity": "Уровень активности",
    "calc.selectLevel": "Выберите уровень",
    "calc.goal": "Цель",
    "calc.lose": "Похудение",
    "calc.maintain": "Поддержание",
    "calc.gain": "Набор массы",
    "calc.pace": "Темп",
    "calc.moderate": "Умеренный",
    "calc.aggressive": "Агрессивный",
    "calc.calculate": "Рассчитать",
    "calc.calculating": "Рассчитываем...",
    "calc.results": "Результаты расчёта",
    "calc.bmr": "Базовый метаболизм (BMR)",
    "calc.tdee": "Поддержание (TDEE)",
    "calc.recommended": "Рекомендовано для цели",
    "calc.kcalDay": "ккал/день",
    "calc.macros": "Рекомендуемые БЖУ",
    "calc.protein": "Белки",
    "calc.fat": "Жиры",
    "calc.carbs": "Углеводы",
    "calc.grams": "г",
    "calc.warning": "Расчёт приблизительный и не учитывает индивидуальные особенности организма. Для точных рекомендаций проконсультируйтесь с врачом или диетологом.",
    "calc.fillForm": "Заполните форму слева",
    "calc.resultsHere": "Результаты расчёта появятся здесь",
    "calc.activity.sedentary": "Сидячий образ жизни",
    "calc.activity.sedentary.desc": "Минимум физической активности",
    "calc.activity.light": "Лёгкая активность",
    "calc.activity.light.desc": "1-3 тренировки в неделю",
    "calc.activity.moderate": "Умеренная активность",
    "calc.activity.moderate.desc": "3-5 тренировок в неделю",
    "calc.activity.high": "Высокая активность",
    "calc.activity.high.desc": "6-7 тренировок в неделю",
    "calc.activity.extreme": "Очень высокая",
    "calc.activity.extreme.desc": "Тяжёлая физическая работа + тренировки",
    "calc.error.age": "Возраст должен быть от 15 до 100 лет",
    "calc.error.height": "Рост должен быть от 100 до 250 см",
    "calc.error.weight": "Вес должен быть от 30 до 300 кг",
    "calc.error.activity": "Выберите уровень активности",
    "calc.error.goal": "Выберите цель",

    // Workouts
    "workout.title": "План тренировок",
    "workout.subtitle": "Персональная программа под ваш тип телосложения",
    "workout.location": "Где тренируетеесь?",
    "workout.home": "Дома",
    "workout.gym": "В зале",
    "workout.equipment": "Доступное оборудование",
    "workout.bodyweight": "Собственный вес",
    "workout.dumbbells": "Гантели",
    "workout.barbell": "Штанга",
    "workout.pullupBar": "Турник",
    "workout.bands": "Резинки",
    "workout.kettlebell": "Гири",
    "workout.level": "Уровень подготовки",
    "workout.beginner": "Новичок",
    "workout.beginner.desc": "Менее 6 месяцев опыта",
    "workout.intermediate": "Средний",
    "workout.intermediate.desc": "6 месяцев - 2 года",
    "workout.advanced": "Продвинутый",
    "workout.advanced.desc": "Более 2 лет опыта",
    "workout.daysPerWeek": "Дней в неделю",
    "workout.howManyDays": "Сколько дней?",
    "workout.days": "дней",
    "workout.generate": "Создать план",
    "workout.generating": "Генерируем...",
    "workout.yourPlan": "Ваш план на неделю",
    "workout.regenerate": "Пересоздать",
    "workout.setupLeft": "Настройте параметры слева",
    "workout.planHere": "План тренировок появится здесь после генерации",
    "workout.rest": "Отдых",
    "workout.min": "мин",
    "workout.bodyType": "Тип телосложения",
    "workout.bodyType.hint": "Эктоморф — худощавый, сложно набирает массу. Мезоморф — атлетичный, легко набирает мышцы. Эндоморф — склонен к полноте, медленный метаболизм.",
    "workout.selectBodyType": "Выберите тип",
    "workout.ectomorph": "Эктоморф",
    "workout.ectomorph.desc": "Худощавое телосложение, быстрый метаболизм",
    "workout.mesomorph": "Мезоморф",
    "workout.mesomorph.desc": "Атлетичное телосложение, легко набирает мышцы",
    "workout.endomorph": "Эндоморф",
    "workout.endomorph.desc": "Склонность к полноте, медленный метаболизм",

    // Workout types
    "workout.fullBody": "Всё тело",
    "workout.upperBody": "Верхняя часть тела",
    "workout.lowerBody": "Нижняя часть тела",
    "workout.legsCore": "Ноги + Кор",
    "workout.pushDay": "День жима",
    "workout.pullDay": "День тяги",
    "workout.legs": "Ноги",
    "workout.shoulders": "Плечи",
    "workout.chestTriceps": "Грудь + Трицепс",
    "workout.backBiceps": "Спина + Бицепс",
    "workout.chestShoulders": "Грудь + Плечи",
    "workout.backArms": "Спина + Руки",
    "workout.chest": "Грудь",
    "workout.back": "Спина",
    "workout.arms": "Руки",
    "workout.fullBodyCircuit": "Круговая тренировка",
    "workout.lowerBodyCore": "Ноги + Кор",
    "workout.hiitCircuit": "HIIT круговая",
    "workout.upperBodyMetabolic": "Верх тела (метаболическая)",

    // CTA
    "cta.title": "Начните свой путь к форме уже сегодня",
    "cta.subtitle": "Присоединяйтесь к тысячам людей, которые уже достигли своих целей",
    "cta.benefit1": "Бесплатный расчёт калорий",
    "cta.benefit2": "200+ упражнений с техникой",
    "cta.benefit3": "Персональный план тренировок",
    "cta.benefit4": "Программы по типу тела",
    "cta.start": "Начать бесплатно",

    // Preview
    "preview.calculator": "Калькулятор калорий",
    "preview.calcTitle": "Персональный расчёт нормы калорий",
    "preview.calcDesc": "Введите свои данные и получите точный расчёт дневной нормы калорий, белков, жиров и углеводов для вашей цели.",
    "preview.yourGoal": "Ваша цель",
    "preview.calcNorm": "Рассчитать свою норму",
    "preview.workoutPlan": "План тренировок",
    "preview.workoutTitle": "Готовые программы под ваш тип тела",
    "preview.workoutDesc": "Выберите тип телосложения, место тренировки, доступное оборудование и уровень — получите персональную программу.",
    "preview.createPlan": "Создать план тренировок",
    "preview.day1": "День 1: Верх тела",

    // Days
    "day.monday": "Понедельник",
    "day.tuesday": "Вторник",
    "day.wednesday": "Среда",
    "day.thursday": "Четверг",
    "day.friday": "Пятница",
    "day.saturday": "Суббота",
    "day.sunday": "Воскресенье",

    // Exercises - Basic
    "exercise.pushups": "Отжимания",
    "exercise.pullups": "Подтягивания",
    "exercise.shoulderPress": "Жим гантелей стоя",
    "exercise.flyes": "Разведение гантелей",
    "exercise.squats": "Приседания",
    "exercise.lunges": "Выпады",
    "exercise.romanianDeadlift": "Румынская тяга",
    "exercise.calfRaises": "Подъёмы на носки",
    "exercise.dumbbellBenchPress": "Жим лёжа с гантелями",
    "exercise.dumbbellRow": "Тяга гантели в наклоне",
    "exercise.bicepCurls": "Подъём гантелей на бицепс",
    "exercise.tricepExtension": "Французский жим",
    "exercise.bulgarianSplitSquats": "Болгарские выпады",
    "exercise.gobletSquats": "Гоблет приседания",
    "exercise.plank": "Планка",
    "exercise.crunches": "Скручивания",

    // Exercises - Advanced
    "exercise.benchPress": "Жим лёжа со штангой",
    "exercise.inclineBenchPress": "Жим лёжа на наклонной",
    "exercise.inclineDumbbellPress": "Жим гантелей на наклонной",
    "exercise.barbellRow": "Тяга штанги в наклоне",
    "exercise.overheadPress": "Армейский жим",
    "exercise.deadlift": "Становая тяга",
    "exercise.frontSquats": "Фронтальные приседания",
    "exercise.legPress": "Жим ногами",
    "exercise.legCurl": "Сгибание ног",
    "exercise.legExtension": "Разгибание ног",
    "exercise.latPulldown": "Тяга верхнего блока",
    "exercise.seatedRow": "Тяга горизонтального блока",
    "exercise.cableFlyes": "Сведение в кроссовере",
    "exercise.facePulls": "Тяга к лицу",
    "exercise.lateralRaises": "Махи гантелями в стороны",
    "exercise.rearDeltFlyes": "Махи на заднюю дельту",
    "exercise.dips": "Отжимания на брусьях",
    "exercise.tricepDips": "Отжимания на трицепс",
    "exercise.tricepPushdown": "Разгибание на блоке",
    "exercise.closeGripBench": "Жим узким хватом",
    "exercise.skullCrushers": "Французский жим лёжа",
    "exercise.overheadTricepExtension": "Разгибание над головой",
    "exercise.tricepKickbacks": "Разгибание в наклоне",
    "exercise.barbellCurl": "Подъём штанги на бицепс",
    "exercise.hammerCurls": "Молотковые сгибания",
    "exercise.preacherCurl": "Сгибания на скамье Скотта",
    "exercise.concentrationCurl": "Концентрированные сгибания",
    "exercise.hipThrust": "Ягодичный мост со штангой",
    "exercise.walkingLunges": "Выпады в движении",
    "exercise.hackSquat": "Гакк-приседания",
    "exercise.lyingLegCurl": "Сгибание ног лёжа",
    "exercise.standingCalfRaise": "Подъём на носки стоя",
    "exercise.seatedCalfRaise": "Подъём на носки сидя",
    "exercise.weightedPullups": "Подтягивания с весом",
    "exercise.tBarRow": "Тяга Т-грифа",
    "exercise.arnoldPress": "Жим Арнольда",
    "exercise.shrugs": "Шраги",
    "exercise.uprightRow": "Тяга к подбородку",
    "exercise.dumbbellShoulderPress": "Жим гантелей сидя",
    "exercise.dumbbellFlyes": "Разведение гантелей лёжа",
    "exercise.cableCrossover": "Кроссовер",
    "exercise.straightArmPulldown": "Пуловер на блоке",
    "exercise.chinups": "Подтягивания обратным хватом",
    "exercise.reverseCurls": "Обратные сгибания",
    "exercise.diamondPushups": "Алмазные отжимания",
    
    // Cardio/HIIT exercises
    "exercise.jumpingJacks": "Джампинг Джек",
    "exercise.mountainClimbers": "Скалолаз",
    "exercise.burpees": "Бёрпи",
    "exercise.stepUps": "Подъёмы на платформу",
    "exercise.inclinePushups": "Отжимания с наклоном",
    "exercise.bicycleCrunches": "Велосипед",
    "exercise.highKnees": "Бег на месте",
    "exercise.kettlebellSwings": "Махи гирей",
    "exercise.boxJumps": "Прыжки на тумбу",
    "exercise.battleRopes": "Канаты",
    "exercise.cableCrunch": "Скручивания на блоке",
    "exercise.russianTwists": "Русские скручивания",
    "exercise.hangingLegRaise": "Подъём ног в висе",
    "exercise.medicBallSlams": "Удары медболом",
    "exercise.prowlerPush": "Толкание саней",

    // Muscles
    "muscle.chest": "Грудь",
    "muscle.triceps": "Трицепс",
    "muscle.back": "Спина",
    "muscle.biceps": "Бицепс",
    "muscle.shoulders": "Плечи",
    "muscle.quads": "Квадрицепс",
    "muscle.glutes": "Ягодицы",
    "muscle.legs": "Ноги",
    "muscle.hamstrings": "Бицепс бедра",
    "muscle.calves": "Икры",
    "muscle.core": "Кор",
    "muscle.abs": "Пресс",
    "muscle.rearDelts": "Задняя дельта",
    "muscle.traps": "Трапеции",
    "muscle.lats": "Широчайшие",
    "muscle.forearms": "Предплечья",
    "muscle.obliques": "Косые мышцы",
    "muscle.fullBody": "Всё тело",

    // Common
    "common.attention": "Обратите внимание",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.calculator": "Calculator",
    "nav.workouts": "Workouts",
    
    // Hero
    "hero.badge": "Personal calculation in 1 minute",
    "hero.title": "Calculate your daily",
    "hero.titleHighlight": "calorie",
    "hero.titleEnd": "intake and get a workout plan",
    "hero.subtitle": "Science-based formulas and personalized recommendations to achieve your goals — weight loss, muscle gain, or weight maintenance",
    "hero.cta": "Start Calculation",
    "hero.secondary": "View Workouts",
    "hero.users": "users",
    "hero.exercises": "exercises",
    "hero.rating": "rating",

    // Features
    "features.title": "Everything for your results",
    "features.subtitle": "Three key tools that work together to help you reach your goal",
    "features.formula.title": "Accurate Formula",
    "features.formula.desc": "Mifflin-St Jeor calculation based on your activity level, age, and goals. Get personalized recommendations for calories and macros.",
    "features.workouts.title": "Personal Workouts",
    "features.workouts.desc": "Ready-made programs for home and gym based on your body type. Choose equipment, fitness level — and get a weekly plan.",
    "features.tracking.title": "Body Type Programs",
    "features.tracking.desc": "Programs adapted for ectomorphs, mesomorphs, and endomorphs according to ACSM and NSCA guidelines.",

    // Calculator
    "calc.title": "Calorie Calculator",
    "calc.formula": "Mifflin-St Jeor Formula",
    "calc.gender": "Gender",
    "calc.male": "Male",
    "calc.female": "Female",
    "calc.age": "Age",
    "calc.height": "Height",
    "calc.weight": "Weight",
    "calc.activity": "Activity Level",
    "calc.selectLevel": "Select level",
    "calc.goal": "Goal",
    "calc.lose": "Weight Loss",
    "calc.maintain": "Maintain",
    "calc.gain": "Muscle Gain",
    "calc.pace": "Pace",
    "calc.moderate": "Moderate",
    "calc.aggressive": "Aggressive",
    "calc.calculate": "Calculate",
    "calc.calculating": "Calculating...",
    "calc.results": "Calculation Results",
    "calc.bmr": "Basal Metabolic Rate (BMR)",
    "calc.tdee": "Maintenance (TDEE)",
    "calc.recommended": "Recommended for your goal",
    "calc.kcalDay": "kcal/day",
    "calc.macros": "Recommended Macros",
    "calc.protein": "Protein",
    "calc.fat": "Fat",
    "calc.carbs": "Carbs",
    "calc.grams": "g",
    "calc.warning": "This is an approximate calculation and doesn't account for individual characteristics. For precise recommendations, consult a doctor or nutritionist.",
    "calc.fillForm": "Fill out the form on the left",
    "calc.resultsHere": "Results will appear here",
    "calc.activity.sedentary": "Sedentary lifestyle",
    "calc.activity.sedentary.desc": "Minimal physical activity",
    "calc.activity.light": "Light activity",
    "calc.activity.light.desc": "1-3 workouts per week",
    "calc.activity.moderate": "Moderate activity",
    "calc.activity.moderate.desc": "3-5 workouts per week",
    "calc.activity.high": "High activity",
    "calc.activity.high.desc": "6-7 workouts per week",
    "calc.activity.extreme": "Very high",
    "calc.activity.extreme.desc": "Heavy physical work + training",
    "calc.error.age": "Age must be between 15 and 100",
    "calc.error.height": "Height must be between 100 and 250 cm",
    "calc.error.weight": "Weight must be between 30 and 300 kg",
    "calc.error.activity": "Select activity level",
    "calc.error.goal": "Select goal",

    // Workouts
    "workout.title": "Workout Plan",
    "workout.subtitle": "Personal program based on your body type",
    "workout.location": "Where do you train?",
    "workout.home": "At Home",
    "workout.gym": "At Gym",
    "workout.equipment": "Available Equipment",
    "workout.bodyweight": "Bodyweight",
    "workout.dumbbells": "Dumbbells",
    "workout.barbell": "Barbell",
    "workout.pullupBar": "Pull-up Bar",
    "workout.bands": "Resistance Bands",
    "workout.kettlebell": "Kettlebells",
    "workout.level": "Fitness Level",
    "workout.beginner": "Beginner",
    "workout.beginner.desc": "Less than 6 months experience",
    "workout.intermediate": "Intermediate",
    "workout.intermediate.desc": "6 months - 2 years",
    "workout.advanced": "Advanced",
    "workout.advanced.desc": "More than 2 years experience",
    "workout.daysPerWeek": "Days per week",
    "workout.howManyDays": "How many days?",
    "workout.days": "days",
    "workout.generate": "Create Plan",
    "workout.generating": "Generating...",
    "workout.yourPlan": "Your weekly plan",
    "workout.regenerate": "Regenerate",
    "workout.setupLeft": "Set up parameters on the left",
    "workout.planHere": "Workout plan will appear here after generation",
    "workout.rest": "Rest",
    "workout.min": "min",
    "workout.bodyType": "Body Type",
    "workout.bodyType.hint": "Ectomorph — lean build, hard to gain mass. Mesomorph — athletic, gains muscle easily. Endomorph — tends to store fat, slower metabolism.",
    "workout.selectBodyType": "Select type",
    "workout.ectomorph": "Ectomorph",
    "workout.ectomorph.desc": "Lean build, fast metabolism",
    "workout.mesomorph": "Mesomorph",
    "workout.mesomorph.desc": "Athletic build, gains muscle easily",
    "workout.endomorph": "Endomorph",
    "workout.endomorph.desc": "Tends to store fat, slower metabolism",

    // Workout types
    "workout.fullBody": "Full Body",
    "workout.upperBody": "Upper Body",
    "workout.lowerBody": "Lower Body",
    "workout.legsCore": "Legs + Core",
    "workout.pushDay": "Push Day",
    "workout.pullDay": "Pull Day",
    "workout.legs": "Legs",
    "workout.shoulders": "Shoulders",
    "workout.chestTriceps": "Chest + Triceps",
    "workout.backBiceps": "Back + Biceps",
    "workout.chestShoulders": "Chest + Shoulders",
    "workout.backArms": "Back + Arms",
    "workout.chest": "Chest",
    "workout.back": "Back",
    "workout.arms": "Arms",
    "workout.fullBodyCircuit": "Full Body Circuit",
    "workout.lowerBodyCore": "Lower Body + Core",
    "workout.hiitCircuit": "HIIT Circuit",
    "workout.upperBodyMetabolic": "Upper Body (Metabolic)",

    // CTA
    "cta.title": "Start your fitness journey today",
    "cta.subtitle": "Join thousands of people who have already achieved their goals",
    "cta.benefit1": "Free calorie calculation",
    "cta.benefit2": "200+ exercises with technique",
    "cta.benefit3": "Personal workout plan",
    "cta.benefit4": "Body type programs",
    "cta.start": "Start for Free",

    // Preview
    "preview.calculator": "Calorie Calculator",
    "preview.calcTitle": "Personal calorie intake calculation",
    "preview.calcDesc": "Enter your data and get an accurate calculation of daily calorie intake, protein, fat, and carbs for your goal.",
    "preview.yourGoal": "Your goal",
    "preview.calcNorm": "Calculate your intake",
    "preview.workoutPlan": "Workout Plan",
    "preview.workoutTitle": "Ready programs for your body type",
    "preview.workoutDesc": "Choose body type, training location, available equipment and level — get a personal weekly program.",
    "preview.createPlan": "Create workout plan",
    "preview.day1": "Day 1: Upper Body",

    // Days
    "day.monday": "Monday",
    "day.tuesday": "Tuesday",
    "day.wednesday": "Wednesday",
    "day.thursday": "Thursday",
    "day.friday": "Friday",
    "day.saturday": "Saturday",
    "day.sunday": "Sunday",

    // Exercises - Basic
    "exercise.pushups": "Push-ups",
    "exercise.pullups": "Pull-ups",
    "exercise.shoulderPress": "Dumbbell Shoulder Press",
    "exercise.flyes": "Dumbbell Flyes",
    "exercise.squats": "Squats",
    "exercise.lunges": "Lunges",
    "exercise.romanianDeadlift": "Romanian Deadlift",
    "exercise.calfRaises": "Calf Raises",
    "exercise.dumbbellBenchPress": "Dumbbell Bench Press",
    "exercise.dumbbellRow": "Dumbbell Row",
    "exercise.bicepCurls": "Bicep Curls",
    "exercise.tricepExtension": "Tricep Extension",
    "exercise.bulgarianSplitSquats": "Bulgarian Split Squats",
    "exercise.gobletSquats": "Goblet Squats",
    "exercise.plank": "Plank",
    "exercise.crunches": "Crunches",

    // Exercises - Advanced
    "exercise.benchPress": "Barbell Bench Press",
    "exercise.inclineBenchPress": "Incline Bench Press",
    "exercise.inclineDumbbellPress": "Incline Dumbbell Press",
    "exercise.barbellRow": "Barbell Row",
    "exercise.overheadPress": "Overhead Press",
    "exercise.deadlift": "Deadlift",
    "exercise.frontSquats": "Front Squats",
    "exercise.legPress": "Leg Press",
    "exercise.legCurl": "Leg Curl",
    "exercise.legExtension": "Leg Extension",
    "exercise.latPulldown": "Lat Pulldown",
    "exercise.seatedRow": "Seated Row",
    "exercise.cableFlyes": "Cable Flyes",
    "exercise.facePulls": "Face Pulls",
    "exercise.lateralRaises": "Lateral Raises",
    "exercise.rearDeltFlyes": "Rear Delt Flyes",
    "exercise.dips": "Dips",
    "exercise.tricepDips": "Tricep Dips",
    "exercise.tricepPushdown": "Tricep Pushdown",
    "exercise.closeGripBench": "Close Grip Bench",
    "exercise.skullCrushers": "Skull Crushers",
    "exercise.overheadTricepExtension": "Overhead Tricep Extension",
    "exercise.tricepKickbacks": "Tricep Kickbacks",
    "exercise.barbellCurl": "Barbell Curl",
    "exercise.hammerCurls": "Hammer Curls",
    "exercise.preacherCurl": "Preacher Curl",
    "exercise.concentrationCurl": "Concentration Curl",
    "exercise.hipThrust": "Hip Thrust",
    "exercise.walkingLunges": "Walking Lunges",
    "exercise.hackSquat": "Hack Squat",
    "exercise.lyingLegCurl": "Lying Leg Curl",
    "exercise.standingCalfRaise": "Standing Calf Raise",
    "exercise.seatedCalfRaise": "Seated Calf Raise",
    "exercise.weightedPullups": "Weighted Pull-ups",
    "exercise.tBarRow": "T-Bar Row",
    "exercise.arnoldPress": "Arnold Press",
    "exercise.shrugs": "Shrugs",
    "exercise.uprightRow": "Upright Row",
    "exercise.dumbbellShoulderPress": "Dumbbell Shoulder Press",
    "exercise.dumbbellFlyes": "Dumbbell Flyes",
    "exercise.cableCrossover": "Cable Crossover",
    "exercise.straightArmPulldown": "Straight Arm Pulldown",
    "exercise.chinups": "Chin-ups",
    "exercise.reverseCurls": "Reverse Curls",
    "exercise.diamondPushups": "Diamond Push-ups",
    
    // Cardio/HIIT exercises
    "exercise.jumpingJacks": "Jumping Jacks",
    "exercise.mountainClimbers": "Mountain Climbers",
    "exercise.burpees": "Burpees",
    "exercise.stepUps": "Step Ups",
    "exercise.inclinePushups": "Incline Push-ups",
    "exercise.bicycleCrunches": "Bicycle Crunches",
    "exercise.highKnees": "High Knees",
    "exercise.kettlebellSwings": "Kettlebell Swings",
    "exercise.boxJumps": "Box Jumps",
    "exercise.battleRopes": "Battle Ropes",
    "exercise.cableCrunch": "Cable Crunch",
    "exercise.russianTwists": "Russian Twists",
    "exercise.hangingLegRaise": "Hanging Leg Raise",
    "exercise.medicBallSlams": "Medicine Ball Slams",
    "exercise.prowlerPush": "Prowler Push",

    // Muscles
    "muscle.chest": "Chest",
    "muscle.triceps": "Triceps",
    "muscle.back": "Back",
    "muscle.biceps": "Biceps",
    "muscle.shoulders": "Shoulders",
    "muscle.quads": "Quads",
    "muscle.glutes": "Glutes",
    "muscle.legs": "Legs",
    "muscle.hamstrings": "Hamstrings",
    "muscle.calves": "Calves",
    "muscle.core": "Core",
    "muscle.abs": "Abs",
    "muscle.rearDelts": "Rear Delts",
    "muscle.traps": "Traps",
    "muscle.lats": "Lats",
    "muscle.forearms": "Forearms",
    "muscle.obliques": "Obliques",
    "muscle.fullBody": "Full Body",

    // Common
    "common.attention": "Please note",
  },
  cs: {
    // Navigation
    "nav.home": "Domů",
    "nav.calculator": "Kalkulačka",
    "nav.workouts": "Tréninky",
    
    // Hero
    "hero.badge": "Osobní výpočet za 1 minutu",
    "hero.title": "Vypočítej svůj denní příjem",
    "hero.titleHighlight": "kalorií",
    "hero.titleEnd": "a získej tréninkový plán",
    "hero.subtitle": "Vědecky podložené vzorce a personalizovaná doporučení pro dosažení vašich cílů — hubnutí, nabírání svalů nebo udržení váhy",
    "hero.cta": "Zahájit výpočet",
    "hero.secondary": "Zobrazit tréninky",
    "hero.users": "uživatelů",
    "hero.exercises": "cvičení",
    "hero.rating": "hodnocení",

    // Features
    "features.title": "Vše pro váš výsledek",
    "features.subtitle": "Tři klíčové nástroje, které spolupracují k dosažení vašeho cíle",
    "features.formula.title": "Přesný vzorec",
    "features.formula.desc": "Výpočet podle Mifflin-St Jeor s ohledem na vaši úroveň aktivity, věk a cíle. Získejte personalizovaná doporučení pro kalorie a makra.",
    "features.workouts.title": "Osobní tréninky",
    "features.workouts.desc": "Připravené programy pro domácí cvičení i posilovnu podle typu postavy. Vyberte vybavení, úroveň fitness — a získejte týdenní plán.",
    "features.tracking.title": "Programy podle tělesného typu",
    "features.tracking.desc": "Programy přizpůsobené ektomorfům, mezomorfům a endomorfům podle doporučení ACSM a NSCA.",

    // Calculator
    "calc.title": "Kalorická kalkulačka",
    "calc.formula": "Vzorec Mifflin-St Jeor",
    "calc.gender": "Pohlaví",
    "calc.male": "Muž",
    "calc.female": "Žena",
    "calc.age": "Věk",
    "calc.height": "Výška",
    "calc.weight": "Váha",
    "calc.activity": "Úroveň aktivity",
    "calc.selectLevel": "Vyberte úroveň",
    "calc.goal": "Cíl",
    "calc.lose": "Hubnutí",
    "calc.maintain": "Udržení",
    "calc.gain": "Nabírání",
    "calc.pace": "Tempo",
    "calc.moderate": "Mírné",
    "calc.aggressive": "Agresivní",
    "calc.calculate": "Vypočítat",
    "calc.calculating": "Počítám...",
    "calc.results": "Výsledky výpočtu",
    "calc.bmr": "Bazální metabolismus (BMR)",
    "calc.tdee": "Udržování (TDEE)",
    "calc.recommended": "Doporučeno pro váš cíl",
    "calc.kcalDay": "kcal/den",
    "calc.macros": "Doporučená makra",
    "calc.protein": "Bílkoviny",
    "calc.fat": "Tuky",
    "calc.carbs": "Sacharidy",
    "calc.grams": "g",
    "calc.warning": "Toto je přibližný výpočet a nezohledňuje individuální charakteristiky. Pro přesná doporučení se poraďte s lékařem nebo výživovým poradcem.",
    "calc.fillForm": "Vyplňte formulář vlevo",
    "calc.resultsHere": "Výsledky se zobrazí zde",
    "calc.activity.sedentary": "Sedavý životní styl",
    "calc.activity.sedentary.desc": "Minimální fyzická aktivita",
    "calc.activity.light": "Lehká aktivita",
    "calc.activity.light.desc": "1-3 tréninky týdně",
    "calc.activity.moderate": "Střední aktivita",
    "calc.activity.moderate.desc": "3-5 tréninků týdně",
    "calc.activity.high": "Vysoká aktivita",
    "calc.activity.high.desc": "6-7 tréninků týdně",
    "calc.activity.extreme": "Velmi vysoká",
    "calc.activity.extreme.desc": "Těžká fyzická práce + trénink",
    "calc.error.age": "Věk musí být mezi 15 a 100",
    "calc.error.height": "Výška musí být mezi 100 a 250 cm",
    "calc.error.weight": "Váha musí být mezi 30 a 300 kg",
    "calc.error.activity": "Vyberte úroveň aktivity",
    "calc.error.goal": "Vyberte cíl",

    // Workouts
    "workout.title": "Tréninkový plán",
    "workout.subtitle": "Osobní program podle vašeho tělesného typu",
    "workout.location": "Kde cvičíte?",
    "workout.home": "Doma",
    "workout.gym": "V posilovně",
    "workout.equipment": "Dostupné vybavení",
    "workout.bodyweight": "Власная вага",
    "workout.dumbbells": "Činky",
    "workout.barbell": "Činka",
    "workout.pullupBar": "Hrazda",
    "workout.bands": "Posilovací gumy",
    "workout.kettlebell": "Kettlebell",
    "workout.level": "Úroveň fitness",
    "workout.beginner": "Začátečník",
    "workout.beginner.desc": "Méně než 6 měsíců zkušeností",
    "workout.intermediate": "Pokročilý",
    "workout.intermediate.desc": "6 měsíců - 2 roky",
    "workout.advanced": "Expert",
    "workout.advanced.desc": "Více než 2 roky zkušeností",
    "workout.daysPerWeek": "Dní v týdnu",
    "workout.howManyDays": "Kolik dní?",
    "workout.days": "dní",
    "workout.generate": "Vytvořit plán",
    "workout.generating": "Generuji...",
    "workout.yourPlan": "Váš týdenní plán",
    "workout.regenerate": "Přegenerovat",
    "workout.setupLeft": "Nastavte parametry vlevo",
    "workout.planHere": "Tréninkový plán se zobrazí zde po vygenerování",
    "workout.rest": "Odpočinek",
    "workout.min": "min",
    "workout.bodyType": "Typ postavy",
    "workout.bodyType.hint": "Ektomorf — štíhlá postava, těžko nabírá hmotu. Mezomorf — atletická postava, snadno nabírá svaly. Endomorf — náchylnost k ukládání tuku, pomalejší metabolismus.",
    "workout.selectBodyType": "Vyberte typ",
    "workout.ectomorph": "Ektomorf",
    "workout.ectomorph.desc": "Štíhlá postava, rychlý metabolismus",
    "workout.mesomorph": "Mezomorf",
    "workout.mesomorph.desc": "Atletická postava, snadno nabírá svaly",
    "workout.endomorph": "Endomorf",
    "workout.endomorph.desc": "Náchylnost k ukládání tuku, pomalejší metabolismus",

    // Workout types
    "workout.fullBody": "Celé tělo",
    "workout.upperBody": "Horní část těla",
    "workout.lowerBody": "Dolní část těla",
    "workout.legsCore": "Nohy + Core",
    "workout.pushDay": "Push den",
    "workout.pullDay": "Pull den",
    "workout.legs": "Nohy",
    "workout.shoulders": "Ramena",
    "workout.chestTriceps": "Hrudník + Triceps",
    "workout.backBiceps": "Záda + Biceps",
    "workout.chestShoulders": "Hrudník + Ramena",
    "workout.backArms": "Záda + Paže",
    "workout.chest": "Hrudník",
    "workout.back": "Záda",
    "workout.arms": "Paže",
    "workout.fullBodyCircuit": "Kruhový trénink",
    "workout.lowerBodyCore": "Dolní část + Core",
    "workout.hiitCircuit": "HIIT kruhový",
    "workout.upperBodyMetabolic": "Horní část (метаболический)",

    // CTA
    "cta.title": "Začněte svou fitness cestu ještě dnes",
    "cta.subtitle": "Připojte se k tisícům lidí, kteří již dosáhli svých cílů",
    "cta.benefit1": "Bezplatný výpočet kalorií",
    "cta.benefit2": "200+ cvičení s technikou",
    "cta.benefit3": "Osobní tréninkový plán",
    "cta.benefit4": "Programy podle typu postavy",
    "cta.start": "Začít zdarma",

    // Preview
    "preview.calculator": "Kalorická kalkulačka",
    "preview.calcTitle": "Osobní výpočet kalorického příjmu",
    "preview.calcDesc": "Zadejte své údaje a získejte přesný výpočet denního příjmu kalorií, bílkovin, tuků a sacharidů pro váš cíl.",
    "preview.yourGoal": "Váš cíl",
    "preview.calcNorm": "Vypočítat svůj příjem",
    "preview.workoutPlan": "Tréninkový plán",
    "preview.workoutTitle": "Připravené programy podle typu postavy",
    "preview.workoutDesc": "Vyberte typ postavy, místo tréninku, dostupné vybavení a úroveň — získejte osobní týdenní program.",
    "preview.createPlan": "Vytvořit tréninkový plán",
    "preview.day1": "Den 1: Horní část těla",

    // Days
    "day.monday": "Pondělí",
    "day.tuesday": "Úterý",
    "day.wednesday": "Středa",
    "day.thursday": "Čtvrtek",
    "day.friday": "Pátek",
    "day.saturday": "Sobota",
    "day.sunday": "Neděle",

    // Exercises - Basic
    "exercise.pushups": "Kliky",
    "exercise.pullups": "Shyby",
    "exercise.shoulderPress": "Tlak s činkami",
    "exercise.flyes": "Rozpažování s činkami",
    "exercise.squats": "Dřepy",
    "exercise.lunges": "Výpady",
    "exercise.romanianDeadlift": "Rumunský mrtvý tah",
    "exercise.calfRaises": "Výpony na lýtka",
    "exercise.dumbbellBenchPress": "Bench press s činkami",
    "exercise.dumbbellRow": "Přítahy s činkou",
    "exercise.bicepCurls": "Bicepsové zdvihy",
    "exercise.tricepExtension": "Tricepsové extenze",
    "exercise.bulgarianSplitSquats": "Bulgarské dřepy",
    "exercise.gobletSquats": "Goblet dřepy",
    "exercise.plank": "Plank",
    "exercise.crunches": "Zkracovačky",

    // Exercises - Advanced
    "exercise.benchPress": "Bench press",
    "exercise.inclineBenchPress": "Šikmý bench press",
    "exercise.inclineDumbbellPress": "Šikmý tlak s činkami",
    "exercise.barbellRow": "Přítahy s osou",
    "exercise.overheadPress": "Tlak nad hlavu",
    "exercise.deadlift": "Mrtvý tah",
    "exercise.frontSquats": "Přední dřepy",
    "exercise.legPress": "Leg press",
    "exercise.legCurl": "Leg curl",
    "exercise.legExtension": "Leg extension",
    "exercise.latPulldown": "Přítahy kladky",
    "exercise.seatedRow": "Přítahy vsedě",
    "exercise.cableFlyes": "Cable flyes",
    "exercise.facePulls": "Face pulls",
    "exercise.lateralRaises": "Rozpažky",
    "exercise.rearDeltFlyes": "Zadní delty",
    "exercise.dips": "Dipy",
    "exercise.tricepDips": "Tricepsové dipy",
    "exercise.tricepPushdown": "Tricepsové přítahy",
    "exercise.closeGripBench": "Úzký bench",
    "exercise.skullCrushers": "Francouzský tlak",
    "exercise.overheadTricepExtension": "Extenze nad hlavou",
    "exercise.tricepKickbacks": "Tricepsové výkopy",
    "exercise.barbellCurl": "Bicepsový zdvih s osou",
    "exercise.hammerCurls": "Kladívkové zdvihy",
    "exercise.preacherCurl": "Scottovy zdvihy",
    "exercise.concentrationCurl": "Koncentrované zdvihy",
    "exercise.hipThrust": "Hip thrust",
    "exercise.walkingLunges": "Výpady v chůzi",
    "exercise.hackSquat": "Hack dřepy",
    "exercise.lyingLegCurl": "Leg curl vleže",
    "exercise.standingCalfRaise": "Výpony vestoje",
    "exercise.seatedCalfRaise": "Výpony vsedě",
    "exercise.weightedPullups": "Shyby s váhou",
    "exercise.tBarRow": "T-bar přítahy",
    "exercise.arnoldPress": "Arnoldův tlak",
    "exercise.shrugs": "Shruggy",
    "exercise.uprightRow": "Přítahy k bradě",
    "exercise.dumbbellShoulderPress": "Tlak s činkami vsedě",
    "exercise.dumbbellFlyes": "Rozpažování vleže",
    "exercise.cableCrossover": "Crossover",
    "exercise.straightArmPulldown": "Přítahy s nataženými pažemi",
    "exercise.chinups": "Shyby nadhmatem",
    "exercise.reverseCurls": "Reverzní zdvihy",
    "exercise.diamondPushups": "Diamantové kliky",
    
    // Cardio/HIIT exercises
    "exercise.jumpingJacks": "Jumping Jacks",
    "exercise.mountainClimbers": "Mountain Climbers",
    "exercise.burpees": "Burpees",
    "exercise.stepUps": "Step ups",
    "exercise.inclinePushups": "Šikmé kliky",
    "exercise.bicycleCrunches": "Kolo",
    "exercise.highKnees": "Vysoká kolena",
    "exercise.kettlebellSwings": "Kettlebell swingy",
    "exercise.boxJumps": "Box jumpy",
    "exercise.battleRopes": "Battle ropes",
    "exercise.cableCrunch": "Cable crunch",
    "exercise.russianTwists": "Ruské rotace",
    "exercise.hangingLegRaise": "Zdvihy nohou ve visu",
    "exercise.medicBallSlams": "Medicine ball slamy",
    "exercise.prowlerPush": "Prowler push",

    // Muscles
    "muscle.chest": "Hrudník",
    "muscle.triceps": "Triceps",
    "muscle.back": "Záda",
    "muscle.biceps": "Biceps",
    "muscle.shoulders": "Ramena",
    "muscle.quads": "Čtyřhlavý sval",
    "muscle.glutes": "Hýždě",
    "muscle.legs": "Nohy",
    "muscle.hamstrings": "Zadní strana stehen",
    "muscle.calves": "Lýtka",
    "muscle.core": "Core",
    "muscle.abs": "Břicho",
    "muscle.rearDelts": "Zadní delty",
    "muscle.traps": "Trapézy",
    "muscle.lats": "Latissimus",
    "muscle.forearms": "Předloktí",
    "muscle.obliques": "Šikmé břišní",
    "muscle.fullBody": "Celé tělo",

    // Common
    "common.attention": "Upozornění",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ru";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}